spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-huangxy-dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-huangxy-test